export const ORDER_LIST = [
  {
    id: '00001',
    customer: 'Текунов Иван Сергевич',
    createdAt: '8 сентября',
    total: 13000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00002',
    customer: 'Текунов Иван Сергевич',
    createdAt: '7 сентября',
    total: 3000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00003',
    customer: 'Текунова Алина Сергеевна',
    createdAt: '7 сентября',
    total: 31000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00004',
    customer: 'Текунова Алина Сергеевна',
    createdAt: '6 сентября',
    total: 8000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00005',
    customer: 'Текунова Анастасия Сергеевна',
    createdAt: '6 сентября',
    total: 8000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00006',
    customer: 'Текунов Иван Сергевич',
    createdAt: '8 сентября',
    total: 13000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00007',
    customer: 'Текунов Иван Сергевич',
    createdAt: '7 сентября',
    total: 3000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00008',
    customer: 'Текунова Алина Сергеевна',
    createdAt: '7 сентября',
    total: 31000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00009',
    customer: 'Текунова Алина Сергеевна',
    createdAt: '6 сентября',
    total: 8000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
  {
    id: '00010',
    customer: 'Текунова Анастасия Сергеевна',
    createdAt: '6 сентября',
    total: 8000,
    status: 'Ожидание',
    deliveryMethod: 'СДЭК до двери',
  },
];
